#!/usr/bin/env bash
# Fizzbuzz!

for f in {1..100}
do
	if (( f % 15 == 0 ))
	then
		echo "FizzBuzz"
	elif (( f % 5 == 0 ))
	then
		echo "Buzz"
	elif (( f % 3 == 0 ))
	then
		echo "Fizz"
	else
		echo $f
	fi
done
