#!/usr/bin/env bash
# The script displays "Best School" 10 times but prints
# "bad luck" on the 4th iteration, "good luck" on the
# 8th iteration

x=0

while [ $x -lt 10 ]
do
	((x++))
	if [[ $x -eq 4 ]]
	then
		echo "bad luck"
	elif [[ $x -eq 8 ]]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
