#!/usr/bin/env bash
# To file or not to file
if test -e "school"
then
	echo "school file exists"
	if test -s "school" # file is empty
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if test -f "school" # file is regular
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
